import * as THREE from 'three';
import { Track } from './Track.js';
import { RoadMesh } from './RoadMesh.js';
import { TrackBarriers } from './TrackBarriers.js';
import { TrackFurniture } from './TrackFurniture.js';
import { makeProfile, profileAt, lerpProfile, surfaceDy, surfaceSlope, bandAt, SURFACES, VERGE_W } from './RoadProfile.js';
import { makeRng, clamp } from '../core/MathX.js';

/**
 * Track, ground queries, barriers, props. See CONTRACTS.md §7.
 *
 * The hot path here is `sampleGround`, which physics calls once per wheel per tick — about
 * 7 700 times a second with a full grid at 120 Hz. It is written to allocate nothing: the
 * projection, the interpolated cross-section profile and the returned record are all long-lived
 * scratch objects, and the returned `normal` is a shared Vector3 that callers must copy out
 * before the next call (physics already does). Measured cost is ~0.5 us per call.
 */
export class WorldSystem {
  constructor(ctx) {
    this.ctx = ctx;
    this.barriers = [];
    this.props = [];
    this.lights = [];
    this.rng = makeRng(0xc17c17);

    // --- sampleGround scratch. One set, reused forever.
    this._gProj = Track.makeProjection();
    this._gPa = makeProfile();
    this._gPb = makeProfile();
    this._gP = makeProfile();
    this._gQuery = new THREE.Vector3();
    this._gTerra = { h: 0, dhdx: 0, dhdz: 0, inside: false };
    this._gNormal = new THREE.Vector3(0, 1, 0);
    this._gResult = {
      height: 0,
      normal: this._gNormal,
      surface: 'asphalt',
      grip: 1,
      t: 0,
      lateral: 0,
      onTrack: false,
      width: 0,
      hasGround: true,
    };
  }

  async init() {
    const { scene } = this.ctx;
    this.root = new THREE.Group();
    this.root.name = 'World';
    scene.add(this.root);

    this.track = new Track({ laps: 3 });
    this.spawnPoints = this.track.spawnPoints(8);

    this.road = new RoadMesh(this.track, this.ctx).build();
    this.root.add(this.road.group);

    this.barrierBuilder = new TrackBarriers(this.track, this.ctx).build();
    this.barriers = this.barrierBuilder.segments;
    this.root.add(this.barrierBuilder.group);

    this.furniture = new TrackFurniture(this.track, this.ctx).build();
    this.lights.push(...this.furniture.lights);
    this.root.add(this.furniture.group);

    this._buildTerrain();

    if (this.ctx.debug) {
      this.ctx.debug.log?.('track', `${(this.track.length / 1000).toFixed(2)}km`);
    }
    console.info(
      `[track] ${this.track.name}: ${this.track.length.toFixed(0)}m, ` +
        `${this.track.corners.length} corners, road ${this.road.stats.chunks} chunks / ` +
        `${(this.road.stats.tris / 1000).toFixed(0)}k tris, ${this.barriers.length} barrier segments`
    );
    return this;
  }

  /**
   * Terrain beyond the verge. It is generated by *querying the track*, so it always meets the
   * road at exactly the right height however much the circuit climbs — a flat world plane and a
   * circuit with 60 m of elevation are irreconcilable, and the seam is the first thing you see.
   */
  _buildTerrain() {
    const track = this.track;
    const b = track.bounds;
    const pad = 420;
    const cell = 22;
    const x0 = b.min.x - pad;
    const z0 = b.min.z - pad;
    const nx = Math.ceil((b.max.x - b.min.x + pad * 2) / cell);
    const nz = Math.ceil((b.max.z - b.min.z + pad * 2) / cell);

    const pos = new Float32Array((nx + 1) * (nz + 1) * 3);
    const uv = new Float32Array((nx + 1) * (nz + 1) * 2);
    const field = new Float32Array((nx + 1) * (nz + 1));
    // How built-up the ground is here, 0..1. Baked per vertex because it needs the track
    // projection, which is far too expensive to do per fragment. The terrain shader uses it to
    // choose between city hardstanding and open country — without it the whole map is lawn,
    // and a circuit with towers standing on a lawn reads as a golf course, not a city.
    const urban = new Float32Array((nx + 1) * (nz + 1));
    // How PAVED the ground is here, 0..1 — `urban` with the deliberate green space taken back
    // out. This is the same quantity the fragment shader resolves to when it chooses between
    // `built` and `kept`, evaluated on the vertex grid so `sampleGround` can answer with the
    // surface the player is actually looking at. Without it every square metre of hardstanding,
    // service road and parking lot in the city reports as lawn: 0.38 grip on concrete, a gravel
    // rumble over asphalt and green particles off a slab.
    const paved = new Float32Array((nx + 1) * (nz + 1));
    // The city lane fills ground out to ~640 m from the circuit and the skyline takes over at
    // ~1300 m, so everything the player can see between those is town, not countryside.
    const URBAN_R = 620;
    const URBAN_FADE = 420;
    const proj = Track.makeProjection();
    const prof = makeProfile();
    const q = new THREE.Vector3();
    const noise = this.ctx.assets?.noise2D?.bind(this.ctx.assets) ?? (() => 0.5);

    for (let j = 0; j <= nz; j++) {
      for (let i = 0; i <= nx; i++) {
        const x = x0 + i * cell;
        const z = z0 + j * cell;
        track.project(q.set(x, 0, z), -1, proj);
        profileAt(track, proj.index, prof);
        const bar = proj.lateral < 0 ? prof.barL : prof.barR;
        const reach = bar + VERGE_W;
        const edgeDist = Math.abs(proj.lateral) - bar;
        // Follow the verge slope out, then relax into rolling ground. The terrain must meet the
        // road mesh EXACTLY where the road mesh ends (|lateral| = reach) and sit below it
        // everywhere inside, or you get either a visible lip or z-fighting — and sampleGround
        // would disagree with what the player can see.
        const near = surfaceDy(prof, Math.sign(proj.lateral || 1) * Math.min(Math.abs(proj.lateral), reach));
        const sink = -0.5 * (1 - clamp((Math.abs(proj.lateral) - (reach - 5)) / 5, 0, 1));
        let h = proj.height + near + sink;
        // A heightfield cannot describe a void, so the ground is simply removed from inside the
        // bore and banked up on either side of it — the portal then reads as cut-and-cover,
        // which is what most circuit tunnels actually are.
        if (prof.tunnel > 0.25) {
          const inside = Math.abs(proj.lateral) - (bar + 2.5);
          if (inside < 0) h -= 16;
          else h += Math.min(9, inside * 0.55) * prof.tunnel;
        }
        if (edgeDist > VERGE_W) {
          // Relief has to stay *behind* the barriers: a hill that towers over the run-off looks
          // dramatic in plan view and completely hides the circuit from the driver's eye line.
          const d = edgeDist - VERGE_W;
          const fall = Math.min(1, d / 420) ** 2;
          const hills =
            (noise(x * 0.0016, z * 0.0016) - 0.5) * 26 +
            (noise(x * 0.0062, z * 0.0062) - 0.5) * 7;
          h += (hills - 2) * fall;
        }
        // Built-up out to URBAN_R from the circuit, dissolving into open country beyond. The
        // noise only ragges the edge of town; inside it the ground is built everywhere, and
        // green space is chosen in the shader so it lands as parks rather than as leftovers.
        const dist = Math.max(Math.abs(proj.lateral), proj.distance);
        const u = clamp(
          (1 - (dist - URBAN_R) / URBAN_FADE) + (noise(x * 0.0013, z * 0.0013) - 0.5) * 0.9,
          0,
          1
        );

        // Parks are chosen by the shader, so they are chosen HERE with the same function and the
        // same world coordinates — a park the eye can see and a park the tyre can feel have to
        // be the same park, or the fix just swaps one lie for another.
        const park = smoothstep(0.71, 0.88, gnoise(x * 0.0036, z * 0.0036));

        const k = (j * (nx + 1) + i) * 3;
        pos[k] = x;
        pos[k + 1] = h;
        pos[k + 2] = z;
        field[j * (nx + 1) + i] = h;
        urban[j * (nx + 1) + i] = u;
        paved[j * (nx + 1) + i] = u * (1 - park);
        uv[(j * (nx + 1) + i) * 2] = x * 0.02;
        uv[(j * (nx + 1) + i) * 2 + 1] = z * 0.02;
      }
    }
    // Keep the height field for queries: sampleGround must be able to answer truthfully for
    // any XZ in the world, not just for points over the road. `paved` rides along on the same
    // grid so the surface answer is as cheap as the height answer — one bilinear tap, no
    // projection, no allocation. `urban` is the raw built-up mask the shader consumes.
    this.terrain = { x0, z0, cell, nx, nz, h: field, urban, paved };

    const idx = [];
    for (let j = 0; j < nz; j++) {
      for (let i = 0; i < nx; i++) {
        const a = j * (nx + 1) + i;
        idx.push(a, a + nx + 1, a + 1, a + 1, a + nx + 1, a + nx + 2);
      }
    }
    const geo = new THREE.BufferGeometry();
    geo.setAttribute('position', new THREE.BufferAttribute(pos, 3));
    geo.setAttribute('uv', new THREE.BufferAttribute(uv, 2));
    geo.setAttribute('aUrban', new THREE.BufferAttribute(urban, 1));
    geo.setIndex(new THREE.Uint32BufferAttribute(idx, 1));
    geo.computeVertexNormals();
    geo.computeBoundingSphere();

    // White base colour: the shader below writes the albedo, and material.color would multiply
    // into it a second time.
    const mat = new THREE.MeshStandardMaterial({
      color: 0xffffff,
      roughness: 1,
      metalness: 0,
      envMapIntensity: 0.5,
    });
    mat.onBeforeCompile = (sh) => {
      sh.vertexShader = sh.vertexShader
        .replace(
          '#include <common>',
          '#include <common>\nattribute float aUrban;\nvarying vec3 vWP;\nvarying vec3 vNW;\nvarying float vUrb;'
        )
        .replace(
          '#include <begin_vertex>',
          '#include <begin_vertex>\n vWP=(modelMatrix*vec4(transformed,1.0)).xyz;\n vNW=normalize(mat3(modelMatrix)*objectNormal);\n vUrb=aUrban;'
        );
      sh.fragmentShader = sh.fragmentShader
        .replace('#include <common>', `#include <common>
          varying vec3 vWP; varying vec3 vNW; varying float vUrb;
          float gh(vec2 p){ p=fract(p*vec2(127.1,311.7)); p+=dot(p,p+34.2); return fract(p.x*p.y*4093.7); }
          float gn(vec2 p){ vec2 i=floor(p),f=fract(p); f=f*f*(3.-2.*f);
            return mix(mix(gh(i),gh(i+vec2(1,0)),f.x), mix(gh(i+vec2(0,1)),gh(i+vec2(1,1)),f.x), f.y); }`)
        .replace(
          '#include <map_fragment>',
          `#include <map_fragment>
           float n1 = gn(vWP.xz * 0.055) * 0.6 + gn(vWP.xz * 0.17) * 0.4;
           float n2 = gn(vWP.xz * 0.021), n3 = gn(vWP.xz * 0.7);
           float slope = 1.0 - clamp(vNW.y, 0.0, 1.0);

           // ---- open country. Pulled toward olive: the old greens read as fairway even out
           // in the hills, and under a golden-hour key they lit up like a putting green.
           vec3 grass = mix(vec3(0.056,0.064,0.037), vec3(0.090,0.097,0.055), n2);
           vec3 scrub = mix(vec3(0.098,0.092,0.062), vec3(0.132,0.118,0.080), n1);
           vec3 rock  = vec3(0.104,0.099,0.092);
           vec3 rural = mix(grass, scrub, smoothstep(0.42, 0.82, n1));

           // ---- inside the city this is not lawn, it is the ground between the buildings:
           // concrete hardstanding, cracked asphalt, gravel and dirt lots, quantised into
           // plot-sized patches so it reads as parcels of land rather than as noise.
           vec2 plot = floor(vWP.xz / 38.0);
           float ph = gh(plot * 0.41 + 7.3);
           vec3 hard   = vec3(0.083,0.081,0.076) * (0.80 + 0.40 * gn(vWP.xz * 0.085));
           vec3 tarmac = vec3(0.031,0.032,0.036) * (0.72 + 0.60 * gn(vWP.xz * 0.125));
           vec3 gravel = vec3(0.072,0.068,0.060) * (0.78 + 0.44 * n3);
           vec3 soil   = vec3(0.090,0.066,0.041) * (0.74 + 0.55 * gn(vWP.xz * 0.10));
           vec3 built = hard;
           built = mix(built, tarmac, step(0.30, ph));
           built = mix(built, gravel, step(0.58, ph));
           built = mix(built, soil,   step(0.80, ph));
           // slab joints / lot edges on a 6 m grid, dissolved once they fall under a pixel
           vec2 sp = vWP.xz / 6.0;
           vec2 sf = abs(fract(sp) - 0.5);
           float spx = max(fwidth(sp.x), fwidth(sp.y));
           float joint = smoothstep(0.44, 0.5, max(sf.x, sf.y)) * (1.0 - smoothstep(0.10, 0.42, spx));
           built *= 1.0 - joint * 0.34;
           built *= 0.84 + 0.30 * gn(vWP.xz * 0.028);

           // ---- deliberate green space: parks and planted verges, ~1 patch in 8
           float park = smoothstep(0.71, 0.88, gn(vWP.xz * 0.0036));
           vec3 kept = mix(grass, scrub, 0.30) * (0.92 + 0.16 * gn(vWP.xz * 0.4));
           vec3 city = mix(built, kept, park);

           vec3 c = mix(rural, city, clamp(vUrb, 0.0, 1.0));
           c = mix(c, rock, smoothstep(0.34, 0.70, slope));
           c *= 0.88 + n3 * 0.22;
           diffuseColor.rgb *= c * 2.0;`
        )
        .replace(
          '#include <roughnessmap_fragment>',
          `#include <roughnessmap_fragment>
           // hardstanding is not as matte as turf, and it polishes in the wet
           roughnessFactor = mix(roughnessFactor, 0.78, clamp(vUrb, 0.0, 1.0) * 0.75);`
        );
    };
    mat.customProgramCacheKey = () => 'nft-terrain-v2';

    this.ground = new THREE.Mesh(geo, mat);
    this.ground.name = 'Terrain';
    this.ground.receiveShadow = true;
    this.ground.matrixAutoUpdate = false;
    this.root.add(this.ground);
  }

  getStartLine() {
    const cp = this.track.checkpoints[0];
    return { position: cp.position, quaternion: cp.quaternion, width: cp.width };
  }

  /**
   * Bilinear height of the surrounding terrain height field at a world XZ, plus the analytic
   * gradient and how paved the ground is. Written into `out` = { h, dhdx, dhdz, inside, paved }.
   * `inside` is false once the query leaves the generated world, in which case the height is the
   * clamped edge value. `paved` is 0..1: 1 is city hardstanding, 0 is turf or open country.
   */
  terrainAt(x, z, out) {
    const T = this.terrain;
    const o = out || _terraOut;
    if (!T) {
      o.h = 0;
      o.dhdx = 0;
      o.dhdz = 0;
      o.inside = false;
      o.paved = 0;
      return o;
    }
    const fx = (x - T.x0) / T.cell;
    const fz = (z - T.z0) / T.cell;
    o.inside = fx >= 0 && fz >= 0 && fx <= T.nx && fz <= T.nz;
    const cx = clamp(fx, 0, T.nx - 1e-4);
    const cz = clamp(fz, 0, T.nz - 1e-4);
    const i = cx | 0;
    const j = cz | 0;
    const ux = cx - i;
    const uz = cz - j;
    const w = T.nx + 1;
    const h00 = T.h[j * w + i];
    const h10 = T.h[j * w + i + 1];
    const h01 = T.h[(j + 1) * w + i];
    const h11 = T.h[(j + 1) * w + i + 1];
    const a = h00 + (h10 - h00) * ux;
    const b = h01 + (h11 - h01) * ux;
    o.h = a + (b - a) * uz;
    o.dhdx = ((h10 - h00) * (1 - uz) + (h11 - h01) * uz) / T.cell;
    o.dhdz = ((h01 - h00) * (1 - ux) + (h11 - h10) * ux) / T.cell;
    // Same four cells, same weights — the paved mask costs four loads on top of the height.
    const P = T.paved;
    const p0 = P[j * w + i] + (P[j * w + i + 1] - P[j * w + i]) * ux;
    const p1 = P[(j + 1) * w + i] + (P[(j + 1) * w + i + 1] - P[(j + 1) * w + i]) * ux;
    o.paved = p0 + (p1 - p0) * uz;
    return o;
  }

  /**
   * Ground height + normal + surface at a world XZ. See CONTRACTS.md §7.
   *
   * Truthful EVERYWHERE, not just on the asphalt: inside the modelled corridor the height comes
   * from the road cross-section, outside it from the terrain height field, and the two agree
   * exactly at the seam. `hasGround` is false only when the query leaves the generated world,
   * in which case `height` is the clamped edge value rather than a magic number — callers that
   * care (camera boom, respawn) should test the flag.
   *
   * The SURFACE is truthful everywhere too. Inside the corridor it comes from the cross-section
   * band; outside it from the baked hardstanding mask, so the paved half of the city answers
   * `concrete` and only real parkland, verges and open country answer `grass`.
   *
   * ALLOCATION-FREE. The returned record and its `normal` are reused scratch objects owned by
   * WorldSystem — copy anything you need to keep before calling again. Pass `out` to opt out.
   */
  sampleGround(x, z, hint = -1, out = null) {
    const track = this.track;
    const N = track.samples;
    const proj = track.project(this._gQuery.set(x, 0, z), hint, this._gProj);

    const i0 = proj.index;
    const i1 = (i0 + 1) % N;
    const u = proj.u;
    const p = lerpProfile(
      profileAt(track, i0, this._gPa),
      profileAt(track, i1, this._gPb),
      u,
      this._gP
    );

    const reach = (proj.lateral < 0 ? p.barL : p.barR) + VERGE_W;
    // Use the true planar distance as well as the lateral offset: a point far along the tangent
    // (past the end of the nearest segment) can have a small `lateral` and still be nowhere near
    // the circuit, and answering with a road height there is how a camera ends up underground.
    const absL = Math.max(Math.abs(proj.lateral), proj.distance);

    // ---- outside the modelled corridor: the terrain height field is the ground truth
    if (absL > reach) {
      const t = this.terrainAt(x, z, this._gTerra);
      const r2 = out || this._gResult;
      const n2 = out ? (out.normal ||= new THREE.Vector3()) : this._gNormal;
      // surface normal of a height field is normalize(-dh/dx, 1, -dh/dz)
      const il2 = 1 / Math.hypot(t.dhdx, 1, t.dhdz);
      n2.set(-t.dhdx * il2, il2, -t.dhdz * il2);
      const gravelly = (proj.lateral < 0 ? p.typeL : p.typeR) > 0.5 && absL < reach + 8;
      // NOTE: `lat` clamping below is intentionally skipped — this branch never touches it.
      // Past the run-off apron the ground is whatever the terrain bakes as: city hardstanding
      // (concrete slab, service road, lot) or country. Answering `grass` for all of it — which
      // is what this branch used to do, identically from 45 m to 450 m — hands physics 0.38 grip
      // on a paved plaza, audio a gravel rumble over asphalt and VFX green particles off a slab.
      const band2 = gravelly
        ? SURFACES.gravel
        : t.paved > PAVED_MIN
          ? SURFACES.hardstanding
          : SURFACES.grass;
      r2.normal = n2;
      r2.height = t.h;
      r2.surface = band2.surface;
      // Hard surfaces take the full wet penalty and loose ones only part of it, exactly as the
      // corridor branch does. Grass and gravel are both below the threshold, so their wet
      // behaviour is unchanged; concrete now polishes in the rain like the shoulder does.
      r2.grip = band2.grip * (1 - this._wetGripLoss * (band2.grip > 0.7 ? 1 : 0.4));
      r2.t = proj.t;
      r2.lateral = proj.lateral;
      r2.width = p.W;
      r2.onTrack = false;
      r2.hasGround = t.inside;
      return r2;
    }

    const lat = clamp(proj.lateral, -reach, reach);
    const dy = surfaceDy(p, lat);
    const slope = surfaceSlope(p, lat);

    // interpolate the banked basis' vertical components straight out of the baked arrays
    const nrm = track._nrm;
    const upA = track._up;
    const rY = nrm[i0 * 3 + 1] + (nrm[i1 * 3 + 1] - nrm[i0 * 3 + 1]) * u;
    const height = proj.height + rY * lat + (upA[i0 * 3 + 1] + (upA[i1 * 3 + 1] - upA[i0 * 3 + 1]) * u) * dy;

    // normal = normalize(up - right * dDy/dLat), both in world space
    const nx0 = nrm[i0 * 3];
    const nx1 = nrm[i1 * 3];
    const nz0 = nrm[i0 * 3 + 2];
    const nz1 = nrm[i1 * 3 + 2];
    const rx = nx0 + (nx1 - nx0) * u;
    const rz = nz0 + (nz1 - nz0) * u;
    const ux = upA[i0 * 3] + (upA[i1 * 3] - upA[i0 * 3]) * u;
    const uy = upA[i0 * 3 + 1] + (upA[i1 * 3 + 1] - upA[i0 * 3 + 1]) * u;
    const uz = upA[i0 * 3 + 2] + (upA[i1 * 3 + 2] - upA[i0 * 3 + 2]) * u;
    let vx = ux - rx * slope;
    let vy = uy - rY * slope;
    let vz = uz - rz * slope;
    const il = 1 / (Math.hypot(vx, vy, vz) || 1);
    vx *= il;
    vy *= il;
    vz *= il;

    const band = bandAt(p, lat);
    const r = out || this._gResult;
    const n = out ? (out.normal ||= new THREE.Vector3()) : this._gNormal;
    n.set(vx, vy, vz);
    r.normal = n;
    r.height = height;
    r.surface = band.surface;
    r.grip = band.grip * (1 - this._wetGripLoss * (band.grip > 0.7 ? 1 : 0.4));
    r.t = proj.t;
    r.lateral = proj.lateral;
    r.width = p.W;
    r.onTrack = Math.abs(proj.lateral) <= p.W;
    r.hasGround = true;
    return r;
  }

  _wetGripLoss = 0;

  update() {
    const wet = this.ctx.env?.wetness ?? 0;
    if (wet !== this._lastWet) {
      this._lastWet = wet;
      this._wetGripLoss = wet * 0.22;
      this.road?.setWetness(wet);
    }
  }

  onQuality() {}

  dispose() {
    this.road?.dispose();
  }
}

const _terraOut = { h: 0, dhdx: 0, dhdz: 0, inside: false, paved: 0 };

/**
 * Above this much hardstanding the off-corridor ground answers `concrete` instead of `grass`.
 * 0.5 is "more built than not", i.e. the point at which the terrain shader's own mix tips from
 * country to city, so the surface underfoot flips where the surface on screen does.
 */
const PAVED_MIN = 0.5;

/**
 * The terrain shader's value noise, ported verbatim (see `gh`/`gn` in `_buildTerrain`'s fragment
 * chunk). Used ONLY at bake time — the point is that the park patches the shader paints and the
 * park patches `sampleGround` reports are drawn from the same field, not two lookalikes that
 * disagree by half a block. Float precision differs from GLSL by a hair, which can move a park
 * boundary by a metre or two; nothing else depends on it.
 */
function ghash(px, pz) {
  let x = px * 127.1;
  let y = pz * 311.7;
  x -= Math.floor(x);
  y -= Math.floor(y);
  const d = x * (x + 34.2) + y * (y + 34.2);
  x += d;
  y += d;
  const v = x * y * 4093.7;
  return v - Math.floor(v);
}

function gnoise(px, pz) {
  const ix = Math.floor(px);
  const iz = Math.floor(pz);
  let fx = px - ix;
  let fz = pz - iz;
  fx = fx * fx * (3 - 2 * fx);
  fz = fz * fz * (3 - 2 * fz);
  const a = ghash(ix, iz);
  const b = ghash(ix + 1, iz);
  const c = ghash(ix, iz + 1);
  const d = ghash(ix + 1, iz + 1);
  const lo = a + (b - a) * fx;
  return lo + (c + (d - c) * fx - lo) * fz;
}

function smoothstep(e0, e1, x) {
  const t = clamp((x - e0) / (e1 - e0), 0, 1);
  return t * t * (3 - 2 * t);
}
